flags: {}

packages:
- ./adaptive-hashmap/
- ./deps/pcg-random
- ./deps/haskell-lockfree/atomic-primops

extra-deps:
- async-2.1.0
- base-compat-0.9.1
- clock-0.7.2
- cmdargs-0.10.14
- concurrent-extra-0.7.0.10
- data-accessor-0.2.2.7
- data-accessor-transformers-0.2.1.7
- doctest-0.11.0
- entropy-0.3.7
- exceptions-0.8.2.1
- extra-1.4.9
- ghc-paths-0.1.0.9
- gnuplot-0.5.4.1
- hashable-1.2.4.0
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- rdtsc-1.3.0.1
- stm-2.4.4.1
- syb-0.6
- temporary-1.2.0.4
- text-1.2.2.1
- thread-local-storage-0.1.0.4
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.0
- utility-ht-0.0.11
- vector-0.11.0.0

# This expects to use an implementation of GHC with the Compact
# patches. We often use locally installed versions,
# e.g. ~crest-team/opt/ghc-mutable-cnf-0.5/

# compiler-check: newer-minor
# skip-ghc-check: true

# Here we demand ghc-mutable-cnf:0.5:
compiler: ghc-8.1.20160531

# We can try to make our package-resolution deterministic, even though
# we are using a custom version of GHC:
resolver: nightly-2016-06-21

# [2016.06.24] Currently running with ghc-mutable-cnf-0.5.
# You can optionally build with `stack build --docker`:
docker:
  enable: false
  repo: "vikraman/ghc-mutable-cnf:0.5"
