flags: {}

packages:
 - '.'
 # Temporary, need to update hackage:
 - ../haskell-lockfree/atomic-primops-vector

extra-deps:
 - thread-local-storage-0.1.0.3
 - lockfree-queue-0.2.3.1
 - handa-gdata-0.7.0.3
 - hsbencher-1.20.0.5
 - hsbencher-fusion-0.3.15.2

resolver: lts-3.9
