flags: {}

packages:
 - '.'
 # Temporary, need to update hackage:
 - ../haskell-lockfree/atomic-primops-vector
 - ../old_peter_bag_test

extra-deps:
 - thread-local-storage-0.1.0.3
 - lockfree-queue-0.2.3.1
 - chaselev-deque-0.5.0.5

resolver: lts-3.5
