flags: {}

packages:
 - '.'
 # Temporary, need to update hackage:
 # - ../pcg-random

extra-deps:
 - thread-local-storage-0.1.0.3
 - pcg-random-0.1.3.4
 - quicklz-1.5.0.11
 - lz4-0.2.3.1

resolver: lts-7.7
