flags: {}
packages:
- '.'
- ../pcg-random
- ../haskell-lockfree/atomic-primops
extra-deps:
- async-2.0.2
- atomic-primops-0.8.0.2
- cmdargs-0.10.13
- concurrent-extra-0.7.0.10
- doctest-0.10.1
- entropy-0.3.7
- extra-1.4.2
- ghc-paths-0.1.0.9
- hashable-1.2.3.3
- primitive-0.6.1.0
- random-1.1
- syb-0.6
- text-1.2.2.0
- thread-local-storage-0.1.0.3
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.5.1
- stm-2.4.4.1
resolver: ghc-7.11.20160226
