flags: {}
packages:
- '.'
- ../pcg-random
- ../haskell-lockfree/atomic-primops
extra-deps:
- async-2.0.2
- clock-0.6.0.1
- cmdargs-0.10.13
- concurrent-extra-0.7.0.10
- data-accessor-0.2.2.7
- data-accessor-transformers-0.2.1.7
- doctest-0.10.1
- entropy-0.3.7
- exceptions-0.8.2.1
- extra-1.4.2
- ghc-paths-0.1.0.9
- gnuplot-0.5.4.1
- hashable-1.2.3.3
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- rdtsc-1.3.0.1
- stm-2.4.4.1
- syb-0.6
- temporary-1.2.0.4
- text-1.2.2.0
- thread-local-storage-0.1.0.3
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.5.1
- utility-ht-0.0.11
- vector-0.11.0.0
compiler-check: newer-minor
resolver: ghc-7.11
